### ISSUE TITLE
Problems with Threading

### ISSUE THREAD

**Issue by ChristophePRAT** [MarkNader/Breakout-A3C#1]
Hi, I have a few errors when I try your code:

> /home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/skimage/transform/_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
Exception in thread Thread-42:
Traceback (most recent call last):
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-3-66f3f44fa7bc>", line 320, in <lambda>
    worker_work = lambda: worker.work(gamma,sess,coord,saver)
  File "<ipython-input-3-66f3f44fa7bc>", line 206, in work
    s1, reward, done, _ = self.env.step(actions[a])
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/gym/wrappers/time_limit.py", line 31, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 68, in step
    action = self._action_set[a]
IndexError: index 5 is out of bounds for axis 0 with size 4

> Exception in thread Thread-36:
Traceback (most recent call last):
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-3-66f3f44fa7bc>", line 320, in <lambda>
    worker_work = lambda: worker.work(gamma,sess,coord,saver)
  File "<ipython-input-3-66f3f44fa7bc>", line 206, in work
    s1, reward, done, _ = self.env.step(actions[a])
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/gym/wrappers/time_limit.py", line 31, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 68, in step
    action = self._action_set[a]
IndexError: index 5 is out of bounds for axis 0 with size 4

> Exception in thread Thread-41:
Traceback (most recent call last):
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-3-66f3f44fa7bc>", line 320, in <lambda>
    worker_work = lambda: worker.work(gamma,sess,coord,saver)
  File "<ipython-input-3-66f3f44fa7bc>", line 206, in work
    s1, reward, done, _ = self.env.step(actions[a])
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/gym/wrappers/time_limit.py", line 31, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 68, in step
    action = self._action_set[a]
IndexError: index 5 is out of bounds for axis 0 with size 4

> Exception in thread Thread-43:
Traceback (most recent call last):
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-3-66f3f44fa7bc>", line 320, in <lambda>
    worker_work = lambda: worker.work(gamma,sess,coord,saver)
  File "<ipython-input-3-66f3f44fa7bc>", line 206, in work
    s1, reward, done, _ = self.env.step(actions[a])
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/gym/wrappers/time_limit.py", line 31, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 68, in step
    action = self._action_set[a]
IndexError: index 5 is out of bounds for axis 0 with size 4

> Exception in thread Thread-38:
Traceback (most recent call last):
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-3-66f3f44fa7bc>", line 320, in <lambda>
    worker_work = lambda: worker.work(gamma,sess,coord,saver)
  File "<ipython-input-3-66f3f44fa7bc>", line 206, in work
    s1, reward, done, _ = self.env.step(actions[a])
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/gym/wrappers/time_limit.py", line 31, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 68, in step
    action = self._action_set[a]
IndexError: index 4 is out of bounds for axis 0 with size 4

> Exception in thread Thread-37:
Traceback (most recent call last):
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-3-66f3f44fa7bc>", line 320, in <lambda>
    worker_work = lambda: worker.work(gamma,sess,coord,saver)
  File "<ipython-input-3-66f3f44fa7bc>", line 206, in work
    s1, reward, done, _ = self.env.step(actions[a])
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/gym/wrappers/time_limit.py", line 31, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 68, in step
    action = self._action_set[a]
IndexError: index 4 is out of bounds for axis 0 with size 4

> Exception in thread Thread-39:
Traceback (most recent call last):
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-3-66f3f44fa7bc>", line 320, in <lambda>
    worker_work = lambda: worker.work(gamma,sess,coord,saver)
  File "<ipython-input-3-66f3f44fa7bc>", line 206, in work
    s1, reward, done, _ = self.env.step(actions[a])
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/gym/wrappers/time_limit.py", line 31, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 68, in step
    action = self._action_set[a]
IndexError: index 5 is out of bounds for axis 0 with size 4

> Exception in thread Thread-40:
Traceback (most recent call last):
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-3-66f3f44fa7bc>", line 320, in <lambda>
    worker_work = lambda: worker.work(gamma,sess,coord,saver)
  File "<ipython-input-3-66f3f44fa7bc>", line 206, in work
    s1, reward, done, _ = self.env.step(actions[a])
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/gym/wrappers/time_limit.py", line 31, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/kexin/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 68, in step
    action = self._action_set[a]
IndexError: index 4 is out of bounds for axis 0 with size 4

**Comment by MarkNader** [comment]
Did you follow the appropriate installation of openAi gym?
